# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=32, verbose_name='密码')),
                ('admin', models.CharField(choices=[('1', 'admin'), ('2', 'user')], default='2', max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
